<?php

namespace Fobia\Helper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-23 at 22:51:47.
 */
class JSONTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers Fobia\Helper\JSON::encode_lite
     * @todo   Implement testEncode_lite().
     *//*
    public function testEncode_lite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }/**/

    /**
     * @covers Fobia\Helper\JSON::encode
     * @todo   Implement testEncode().
     */
    public function testEncode()
    {
        $this->assertEquals(array('foo' => 'bar'), JSON::decode('{"foo":"bar"}'));
    }/**/

    /**
     * @covers Fobia\Helper\JSON::decode
     * @todo   Implement testDecode().
     */
    public function testDecode()
    {
        $this->assertEquals('{"foo":"bar"}', JSON::encode(array('foo' => 'bar')));
    }/**/

}
